### ISSUE TITLE
XP Tracking

### ISSUE THREAD

**Issue by GalFawkes** [Malkomax/sips-vs#3]
Based on the number of wins, increment an XP counter and develop a + modifier

- [ ] sqlite3 db downloaded
- [ ] orm class
- [ ] ensure fetch/receive is functional
- [ ] only track for Discord users
- [ ] xp scaling system
